//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YVFlashcard.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserLessionWord
    {
        [Key]public int id { get; set; }
        public int wordId { get; set; }
        public int lessionInfoId { get; set; }
    
        public virtual UserLessionInfo UserLessionInfo { get; set; }
        public virtual UserWord UserWord { get; set; }
    }
}
