//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YVFlashcard.Core
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserStudyHistory
    {
        [Key]public int studyHistoryId { get; set; }
        public string type { get; set; }
        public string username { get; set; }
        public int lessionInfoId { get; set; }
        public Nullable<int> numberlearnedWord { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserLessionInfo UserLessionInfo { get; set; }
    }
}
